### ISSUE TITLE
Ingress Api Update again

### ISSUE THREAD

**Issue by goldfinger3** [k-mitevski/terraform-aks#1]
Ingress api has changed from networking.k8s.io/v1beta1 to **networking.k8s.io/v1** with  Kubernetes v1.19
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: hello-kubernetes
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  defaultBackend:
    service:
      name: hello-kubernetes
      port:
        number: 80
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hello-kubernetes
              port: 
                number: 80
```
